export const products = [{id: '1', categoryId: 'Skins', product: 'Skin - Annie', description: 'Innately connected to the magic of the spirit realm, Ahri is a mysterious fox-like vastaya in search of her place in the world. Having become a somewhat reluctant and empathetic predator since entering mortal society, she prefers to manipulate her prey’s emotions before partaking of their life essence—receiving flashes of memory and insight from each soul she consumes.', price: 40, img: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Annie_6.jpg'},
    {id: '2', categoryId: 'Skins', product: 'Skin - Eckko', description: 'Aprodigy from the rough streets of Zaun, Ekko manipulates time to twist any situation to his advantage. Using his own invention, the Z-Drive, he explores the branching possibilities of reality to craft the perfect moment. Though he revels in this freedom, when there’s a threat to his friends, he’ll do anything to defend them. To outsiders, Ekko seems to achieve the impossible the first time, every time.',  price: 50, img: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ekko_19.jpg'},
    {id: '3', categoryId: 'Skins', product: 'Skin - Lulu', description: 'The yordle mage Lulu is known for conjuring dreamlike illusions and fanciful creatures as she roams Runeterra with her fairy companion Pix. Lulu shapes reality on a whim, warping the fabric of the world, and what she views as the constraints of this mundane, physical realm. While others might consider her magic at best unnatural, and at worst dangerous, she believes everyone could use a touch of enchantment.', price: 60, img: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Lulu_14.jpg'},
    {id: '4', categoryId: 'Champions', product: 'Champion - Caitlyn', description: 'Renowned as its finest peacekeeper, Caitlyn is also Piltover’s best shot at ridding the city of its elusive criminal elements. She is often paired with Vi, acting as a cool counterpoint to her partner’s more impetuous nature. Even though she carries a one-of-a-kind hextech rifle, Caitlyn’s most powerful weapon is her superior intellect, allowing her to lay elaborate traps for any lawbreakers foolish enough to operate in the City of Progress.', price: 80, img: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Caitlyn_1.jpg'},
    {id: '5', categoryId: 'Champions', product: 'Champion - Jinx', price: 100, description: 'Amanic and impulsive criminal from Zaun, Jinx lives to wreak havoc without care for the consequences. With an arsenal of deadly weapons, she unleashes the loudest blasts and brightest explosions to leave a trail of mayhem and panic in her wake. Jinx despises boredom, and gleefully brings her own chaotic brand of pandemonium wherever she goes.', img: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Jinx_2.jpg'},
    {id: '6', categoryId: 'Champions', product: 'Champion - Ahri', description: 'Annie is a child mage with immense pyrokinetic power. Even in the shadows of the mountains north of Noxus, she is a magical outlier.',  price: 48, img: 'https://ddragon.leagueoflegends.com/cdn/img/champion/splash/Ahri_3.jpg'},
];

export const bringProducts = new Promise ((resolve, reject) => {
    resolve(products);
});